
name: build-rust-aarch64-linux-dispatch

on:
  workflow_dispatch

jobs:
  get_release:
    # https://github.com/octokit/request-action
    name: Get release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.get_upload_url.outputs.url }}
    steps:
    - uses: octokit/request-action@v2.x
      id: get_latest_release
      with:
        route: GET /repos/{owner}/{repo}/releases/latest
        owner: esp-rs
        repo: rust-build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: get upload url
      id: get_upload_url
      run: |
        url=$(echo "$response" | jq -r '.upload_url')
        echo "::set-output name=url::$url"
      env:
        response:  ${{ steps.get_latest_release.outputs.data }}

  build-idf-rust:
    name: Build IDF Rust for ${{ matrix.os }}
    # needs: create_release
    needs: get_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-m1-self-hosted ]
        include:
        - os: macos-m1-self-hosted
          ARCH: ''
          TARGET: win-x64
          ASSET_PATH: 'build/dist/rust-1.58.0-dev-aarch64-apple-darwin.tar.xz'
          ASSET_NAME: 'rust-1.58.0.0-aarch64-apple-darwin.tar.xz'
          ASSET_CONTENT_TYPE: 'application/x-tar'
          LLVM_ROOT_OPTION: ''
    steps:
      - name: Build with Podman
        run: |
          podman ps >/dev/null 2>/dev/null || podman machine start
          podman run --name rust-linux ubuntu-builder ./build.sh
          podman cp rust-linux:rust/dist dist
          podman container rm rust-linux
          podman machine stop
      - name: Clean up
        run: |
          rm -rf dist
      # - name: Upload Release Asset
      #   id: upload-release-asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ needs.get_release.outputs.upload_url }}
      #     asset_path: ${{ matrix.ASSET_PATH }}
      #     asset_name: ${{ matrix.ASSET_NAME }}
      #     asset_content_type: ${{ matrix.ASSET_CONTENT_TYPE }}

